# Generated by Django 5.2 on 2025-06-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=200)),
                ('prices', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caracteristicas', models.CharField(max_length=250)),
            ],
        ),
    ]
